FROM ubuntu

MAINTAINER tnarik <tnarik@lecafeautomatique.co.uk>

ARG MALMO_VERSION=Malmo-0.17.0-Linux-Ubuntu-15.10-64bit

ENV MALMO_PATH /tmp/malmo_code
ENV MALMO_XSD_PATH ${MALMO_PATH}/Schemas

ENV PYTHONPATH ${MALMO_PATH}/Python_Examples
ENV VNC_PASS vnc_pass

RUN apt-get update && \
  apt-get install -y wget \
      libboost-all-dev libpython2.7 \
      openjdk-8-jdk ffmpeg libav-tools \
      lua5.1 libxerces-c3.1 liblua5.1-0-dev \
      python-tk python-imaging-tk \
      unzip && \
  update-ca-certificates -f && \

  # Xvfb and X11 VNC
  apt-get install -y xvfb x11vnc

RUN apt-get install -y wget \
  build-essential \
  git \
  cmake cmake-qt-gui \
  libboost-all-dev libpython2.7-dev \
  lua5.1 liblua5.1-0-dev \
  openjdk-8-jdk \
  swig \
  xsdcxx libxerces-c-dev \
  doxygen \
  xsltproc \
  ffmpeg \
  python-tk python-imaging-tk && \

  # Mono
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
  echo "deb http://download.mono-project.com/repo/debian wheezy main" | tee /etc/apt/sources.list.d/mono-xamarin.list && \
  echo "deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main" | tee -a /etc/apt/sources.list.d/mono-xamarin.list && \
  apt-get update && \
  apt-get install -y mono-devel && \

  git clone https://github.com/rpavlik/luabind.git /tmp/luabind && \
  cd /tmp/luabind && \
  mkdir build && \
  cd build && \
  cmake -DCMAKE_BUILD_TYPE=Release .. && \
  make && \
  ctest || true && \
  make install && \

  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \

  git clone https://github.com/tnarik/malmo.git /tmp/malmo_code && \
  wget https://raw.githubusercontent.com/bitfehler/xs3p/1b71310dd1e8b9e4087cf6120856c5f701bd336b/xs3p.xsl -P /tmp/malmo_code/Schemas && \
  export MALMO_XSD_PATH=/tmp/malmo_code/Schemas && \
  cd /tmp/malmo_code && \
  mkdir build && \
  cd build && \
  echo "the last one" && \
  cmake -DCMAKE_BUILD_TYPE=Release ..

EXPOSE 5900
EXPOSE 10000

WORKDIR /code

CMD [ "/opt/malmo/malmo_client" ]
